<!-- IMPORTAÇÃO SCRIPTS COM INCLUDE -->
<!--  
    A GRANDE MAIORIA DOS PROJECTOS DE PROGRAMAÇÃO VÃO SEMPRE NECESSITAR DE TER O SEU CÓDIGO "PARTIDO" ENTRE DIFERENTES FICHEIROS. SALVO RARAS EXCEPÇÕES,
     UM PRROJECTO TERÁ DEZENAS OU CENTENAS DE FICHEIROS PARA QUE A APLICAÇÃO FUNCIONE.
     

     ASSIM, ENTRA OS MECAMNISMOS DE IMPORTAÇÃO DE SCRIPTS DENTRO DE OUTROS SCRIIPTS.
     IMPORTAÇÃO PODE SER FEITA RRECORRENDO AO USO DA INSTRUÇÃO INCLUDE


     NOTA: OO INCLUDE, Á SEMELHANÇÁ DO ECHO, ~ÁO CONSTRUÇÕES ESPECIAS DO PHP E NÃO REQUEREM A UTILIZAÇÃO DE PARENTESIS.




-->
<?php

// OS TIPOS DE CAMINHOS INCLUDE
    // CAMINO RELATIVO
    include 'script.php';
    echo '<br>';
    ECHO APP_NAME;
    echo '<br>';
    echo $data->format('d-m-y');
    // CAMINHO DE ÁRVORE
    echo '<br>';
    include '../010/index.php';
    
    // CAMINHO ABSOLUTO
    echo '<br>';
    include 'C:\laragon\www\041\index.php';
    
